### ISSUE TITLE
mvn clean package -Pwildfly-swarm not working

### ISSUE THREAD

**Issue by gregrluck** [microprofile/microprofile-samples#22]
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.193 sec <<< FAILURE! - in io.microprofile.sample.canonical.rest.TopCDsEndpointTest
io.microprofile.sample.canonical.rest.TopCDsEndpointTest  Time elapsed: 3.192 sec  <<< ERROR!
org.jboss.arquillian.container.spi.client.container.DeploymentException: No WildFly Swarm Bootstrap fraction found
Caused by: java.lang.IllegalStateException: No WildFly Swarm Bootstrap fraction found

**Comment by kenfinnigan** [comment]
I just ran `mvn clean package -Pwildfly-swarm` with the latest and it ran fine

**Comment by johnament** [comment]
Are you overriding the repos by any chance? My PR should have fixed a problem if you had never built swarm locally.

**Comment by cmoulliard** [comment]
build works for me. We should close this issue

**Comment by johnament** [comment]
Closing out, feel free to create a new ticket or reopen.
