### ISSUE TITLE
Don't run wildfly by default

### ISSUE THREAD

**Issue by johnament** [microprofile/microprofile-samples#3]
The way the project is structure, wildfly 10 is downloaded by default.  If I activate another profile, I would not expect the wildfly bits to run.

Please wrap wildfly in a profile, activated by default.

**Comment by johnament** [comment]
To understand what I mean, checkout https://github.com/hammock-project/microprofile-samples and run `mvn clean install -Phammock` and see that wildfly still gets downloaded.

**Comment by kenfinnigan** [comment]
I believe this can be closed now?
