### ISSUE TITLE
pooling of External JNDI Resources of payara

### ISSUE THREAD

**Issue by jmegha27** [microprofile/microprofile-samples#31]
Hi 

How to do the connection pooling of external JNDI resources in payara server
does it come under ejb pooling?

**Comment by kenfinnigan** [comment]
If this is a general question regarding the Payara server, then you probably should contact them directly.

This repository is related to MicroProfile samples, not Payara in particular

**Comment by kenfinnigan** [comment]
Closing as not relevant
