### ISSUE TITLE
Don't include wildfly swarm in a non-swarm profile

### ISSUE THREAD

**Issue by johnament** [microprofile/microprofile-samples#4]
The wildfly swarm dependencies are brought in regardless of profile in use.

**Comment by kenfinnigan** [comment]
Not sure this is still the case.

Can you verify @johnament?

**Comment by johnament** [comment]
I don't see any commits around this.

**Comment by kenfinnigan** [comment]
Can you point out where the dependencies are always brought in?

As far as I can see, WildFly Swarm has a depMan entry root and then dep entries in pom.xml for each app but within a profile

**Comment by johnament** [comment]
It looks like its done.  I'll close it out.
